---
title: "Phylogeny Sense Check"
author: "Grant Foster"
date: "2/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ape)
library(phytools)
```


```{r}
load("BIEN_subtree.Rda")

Mammal_trees <- ape::read.nexus(file="Data.nosync/VertLife_FrugMam/output.nex")
Bird_trees <- ape::read.nexus(file="Data.nosync/VertLife_FrugBird/output.nex")

```

```{r}
plant_litter <- PVR::PVRdecomp(phy=BIEN_subtree, type="newick", scale=TRUE)

plant_PhyEig <-data.frame(BIEN_subtree$tip.label, plant_litter@Eigen$vectors[,1:5])
colnames(plant_PhyEig) <- c("Plant_Species", paste(colnames(plant_PhyEig)[2:ncol(plant_PhyEig)], "PlDecomp", sep=""))

sum((round((plant_litter@Eigen$values)/sum((plant_litter@Eigen$values)),3)*100)[1])


pdf(file="Plant_PhyloDecom_Plot.pdf")
par(mfrow=c(3,2))
for(i in 1:5){
plotTree.wBars(BIEN_subtree, setNames(plant_PhyEig[,i+1], plant_PhyEig$Plant_Species), fsize=100, scale=1000, tip.labels=F, lwd=1, width=0.001)
text(paste("Plants; % Var Explained:", sum((round((plant_litter@Eigen$values)/sum((plant_litter@Eigen$values)),3)*100)[i]), sep = " "), 
     x=100, y=500)
}
```

#Bats
```{r}
bat_bones <- PVR::PVRdecomp(phy=Mammal_trees[[1]], type="newick", scale=TRUE)

#sum((round((frug_litter@Eigen$values)/sum((frug_litter@Eigen$values)),3)*100)[1:3]) #first three vectors contain 66.4% of variation!!!
bat_PhyEig <-data.frame(Mammal_trees[[1]]$tip.label, bat_bones@Eigen$vectors[,1:4]) #take first three vectors and make them a dataframe
colnames(bat_PhyEig) <- c("Frugivore_Species", "fc1", "fc2", "fc3", "fc4")


pdf(file="Bat_PhyloDecom_Plot.pdf")
par(mfrow=c(2,2))
for(i in 1:4){
plotTree.wBars(Mammal_trees[[1]], setNames(bat_PhyEig[,i+1], bat_PhyEig$Frugivore_Species), fsize=100, scale=100, tip.labels=F, lwd=1, width=0.001)
text(paste("Bats; % Var Explained:", sum((round((bat_bones@Eigen$values)/sum((bat_bones@Eigen$values)),3)*100)[i]), sep = " "), 
     x=50, y=1)
}


```


```{r}

bird_bones <- PVR::PVRdecomp(phy=Bird_trees[[1]], type="newick", scale=TRUE)

#sum((round((frug_litter@Eigen$values)/sum((frug_litter@Eigen$values)),3)*100)[1:3]) #first three vectors contain 66.4% of variation!!!
bird_PhyEig <-data.frame(Bird_trees[[1]]$tip.label, bird_bones@Eigen$vectors[,1:4]) #take first three vectors and make them a dataframe
colnames(bird_PhyEig) <- c("Frugivore_Species", "fc1", "fc2", "fc3", "fc4")


pdf(file="Bird_PhyloDecom_Plot.pdf", width=11, height=8.5)
par(mfrow=c(2,2))
for(i in 1:4){
plotTree.wBars(Bird_trees[[1]], setNames(bird_PhyEig[,i+1], bird_PhyEig$Frugivore_Species), fsize=0, scale=100, tip.labels=F, lwd=1, width=0.001)
text(paste("Birds; % Var Explained:", sum((round((bird_bones@Eigen$values)/sum((bird_bones@Eigen$values)),3)*100)[i]), sep = " "), 
     x=40, y=1)
}
```

Checking Moran's I
```{r}
bird_w <- 1/cophenetic(Bird_trees[[1]])
diag(bird_w) <- 0

bat_w <- 1/cophenetic(Mammal_trees[[1]])
diag(bat_w) <- 0

plant_w <- 1/cophenetic(BIEN_subtree)
diag(plant_w) <- 0

output <- NULL
for(i in 1:4){
output <- rbind(output, c(i, 
                Moran.I(x=bat_PhyEig[,i+1], w=bat_w, scaled = TRUE)$p.value,
                Moran.I(x=bird_PhyEig[,i+1], w=bird_w, scaled = TRUE)$p.value,
                Moran.I(x=plant_PhyEig[,i+1], w=plant_w, scaled = TRUE)$p.value))
}
colnames(output) <- c("Eigenvalue Rank", "Bats_Morans_I", "Birds_Morans_I", "Plants_Morans_I")

Moran.I(x=plant_PhyEig[,6], w=plant_w)
```

