---
title: "README"
author: "Grant Foster"
date: "9/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Research Questions:
## 1. How well are we able to predict missing frugivory links across diverse taxa?
## 2. How do link prediction methods using trait-based approaches perform compared to phylogenetic models?
## 3. Compared to the entire network, are we able to predict better or worse on particular taxonomic or functional groups, or for more generalist or specialist nodes. 
## 4. If we train network reconstruction methods on only native interactions, how do they perform when applied to nonnative species?


## Methods:
Using Atlantic Forest data from Bello 2021: (7344 links with native plants, 857 nonnative links). Split into test and training sets, and train a variety of network reconstruction model types including: 
a) methods agnostic to node biology (prefferential-attatchment models, hierarchical structure (Clauset 2008)
b )Models incorporating phylogenetic information (in the style of Elmasri 2020)
c) Trait-based methods, and
D) Combinations of the above. 

Comparing the performance of these competing models using network-wide measures of link prediction performance such as AUC will allow us to answer research questions 1&2. We can then hopefully answer question 3 by comparing the accuracy of particular link sets (ex. Can we detect a phylogenetic signal in how well we’re able to predict host sets using a metric like Moran’s I). We can then apply our best fitting link prediction models to the entire set of native hosts, and then test performance on non-native species to evaluate question 4. In addition to the main research questions outlined above, this project also allows us to predict possible unobserved links, as well as how incorporating of those links may influence overall network structure or stability. 

Papers Methods to look at:
