---
title: "Replicate RFs"
author: "Grant Foster"
date: "3/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(randomForest)
library(pROC)
library(magrittr)
```


```{r}
dat <- read.csv("Data.nosync/ATLANTIC_frugivory.csv")
dat %<>% dplyr::filter(., Frugivore_Species != "Carollia castanea") #This bat has an incorrect gape size
dat <- dplyr::select(dat, -ID, -Latitude, -Longitude, -Study_Location, -Precision, -Study_Method, -Study.reference, -Doi.Link, -Frug_Population_Trend, -Frug_Migration_status)

dat %<>% unique(.)
```

```{r}
load("BIEN_subtree.Rda")
Mammal_trees <- ape::read.nexus(file="Data.nosync/VertLife_FrugMam/output.nex")
Bird_trees <- ape::read.nexus(file="Data.nosync/VertLife_FrugBird/output.nex")
```

Make Traits Binary
```{r}

#dat <- dplyr::filter_at(dat, vars(Plant_Form, Frugivory_score, Lipid_Score, Fruit_color, Plant_origin), all_vars(!is.na(.))) #make sure we have scores for all our binary variables

dat %<>% 
  filter(
    across(
      .cols = c(Plant_Form, Frugivory_score, Lipid_Score, Fruit_color, Plant_origin),
      .fns = ~ !is.na(.x)
    )
  ) #Make sure we have scores for all our binary variables

dat %<>% dplyr::filter(., Fruit_color !="") #This Remove blank fruit color entries
dat$Plant_origin[dat$Plant_origin !="native"] <- "nonnative" #condense all nonnative plants into one (can revisit later)

#dat$real <- 1 # note that these are real interactions; important when we expand later

dat_old <- dat
#dat$Frugivory_score <- paste("FrugScore", dat$Frugivory_score, sep="") #Make value names unambiguous as column names
#dat$Lipid_Score <- paste("LipScore", dat$Lipid_Score, sep="")


categories <- list(Forms=unique(dat$Plant_Form), #take the unique entries of our categorical data and save them in a list; (less typing to assign column names based on them below)
                   #Frugivory_score=unique(dat$Frugivory_score),
                   #Lipid_Score=unique(dat$Lipid_Score),
                   Fruit_color=unique(dat$Fruit_color),
                   Plant_origin=unique(dat$Plant_origin)
                   )
dat_old <- dat

dat <- dat %>% mutate(bin=1) %>% pivot_wider(., names_from = Plant_Form, values_from = bin)
#dat <- dat %>% mutate(bin=1) %>% pivot_wider(., names_from = Frugivory_score, values_from = bin)
#dat <- dat %>% mutate(bin=1) %>% pivot_wider(., names_from = Lipid_Score, values_from = bin)
dat <- dat %>% mutate(bin=1) %>% pivot_wider(., names_from = Fruit_color, values_from = bin)
dat <- dat %>% mutate(bin=1) %>% pivot_wider(., names_from = Plant_origin, values_from = bin)


dat[, which(colnames(dat)=="liana"):ncol(dat)][is.na(dat[,which(colnames(dat)=="liana"):ncol(dat)])==TRUE] <- 0 #Replae all NA's in our newly created columns with 0

dat <- left_join(dat, dat_old) #add back in our factor columns just in case we want them later
```
Add Decomposed Plant Phylogeny to dat
```{r}
plant_litter <- PVR::PVRdecomp(phy=BIEN_subtree, type="newick", scale=TRUE)

sum((round((plant_litter@Eigen$values)/sum((plant_litter@Eigen$values)),3)*100)[1:5]) #first three vectors contain about 42.6% of variation :(

plant_PhyEig <-data.frame(BIEN_subtree$tip.label, plant_litter@Eigen$vectors[,1:5])
colnames(plant_PhyEig) <- c("Plant_Species", paste(colnames(plant_PhyEig)[2:ncol(plant_PhyEig)], "PlDecomp", sep=""))

plant_PhyEig$Plant_Species <- gsub(pattern="_", replace=" ", x=plant_PhyEig$Plant_Species)

dat <- left_join(dat, plant_PhyEig, by="Plant_Species")
birds <- dplyr::filter(dat, Frug_Class=="Aves")
```

SVD Function & Add to Birds
```{r}
svData <- function(dat){
mat_assym <- as.data.frame.matrix(table(dat$Frugivore_Species, dat$Plant_Species)) #Rows = Frugivores, Columns = Plants

decomp <- svd(mat_assym)#run svd decomposition
u <- decomp$u #extract first 3 axis
v <- data.frame(decomp$v) #I think this is the right dimension?

plantsSVD <-data.frame(colnames(mat_assym), v[,1], v[,2], v[,3])
colnames(plantsSVD) <- c("Plant_Species", "Psvd1", "Psvd2", "Psvd3")
frugSVD <- data.frame(colnames(t(mat_assym)), u[,1], u[,2], u[,3])
colnames(frugSVD) <- c("Frugivore_Species", "Fsvd1", "Fsvd2", "Fsvd3")

dat_wP <- left_join(dat, plantsSVD, by="Plant_Species")
dat_new <- left_join(dat_wP, frugSVD, by="Frugivore_Species")

return(dat_new)
}

birds <- svData(birds)
```

```{r}
p_phylo <- c("c1PlDecomp", "c2PlDecomp", "c3PlDecomp", "c4PlDecomp")
p_traits <- c("fruit_diameter", "fruit_length", "tree","liana", "palm", "scrub", "yellow", "red", "black", "brown", "green", "LipScore1", "LipScore2", "LipScore3")
p_latent <- c("Psvd1", "Psvd2", "Psvd3")

f_phylo <- c("fc1", "fc2", "fc3")
f_traits <- c("Frug_Body_Mass","Frug_Mean_Gape_Size", "FrugScore1", "FrugScore2", "FrugScore3")
f_latent <- c("Fsvd1", "Fsvd2", "Fsvd3")
```


Random Forest FunctionSetup
```{r}
woodedWalk <- function(dat, FrugTraits, PlantTraits, class_balancing=FALSE, balance_ratio=3, returnTestTrain=FALSE){
  #Set up our data into a fully expanded edgelist
  require(tidyr)
  dat$real <- 1 #make a new column denoting all of these edges are real; important when we expand out to all pairwise connections later
  dat <- dplyr::filter_at(dat, vars(c(FrugTraits, PlantTraits)), all_vars(!is.na(.))) #make sure we have data for all our predictors
  dat <- dplyr::select_at(dat, vars(c(Frugivore_Species, Plant_Species, real, FrugTraits, PlantTraits))) #Select our relevant predictors
  dat %<>% unique(.) #Make sure we only have unique entries
  full_L <- tidyr::expand(dat, Frugivore_Species, Plant_Species) #Expand to include all possible pairwise plant-frugivore interactions.
  full_real <- dplyr::select(dat, Frugivore_Species, Plant_Species, real) %>% left_join(full_L, ., by = c("Frugivore_Species", "Plant_Species")) #notating which of our edges in this expanded data are real 
  full_real$real[is.na(full_real$real)==TRUE] <- 0

  full_real_frugs <- dat[,c("Frugivore_Species", FrugTraits)] %>% unique() %>% left_join(full_real, ., by="Frugivore_Species") #Add in our frugivore traits

  full_real_both <- dat[,c("Plant_Species", PlantTraits)] %>% unique() %>% left_join(full_real_frugs, ., by="Plant_Species") #add in our plant traits
  
  full_real_both$real <- as.factor(full_real_both$real)
  
  if(class_balancing==TRUE){
    # Subsample our edgelist
    ones <- full_real_both %>% dplyr::filter(., real==1)
    #one_IDs <- sample(round(nrow(ones)*0.8), replace=F)
    #testOnes <- ones[-one_IDs,]
    #trainOnes <- ones[one_IDs,]
    
    zeroes <- full_real_both %>% dplyr::filter(., real==0)
    zero_IDs <- sample(x=1:nrow(zeroes), size=nrow(ones)*balance_ratio, replace=F) #Ratio of train to test 1:3
    keptZeroes <- zeroes[zero_IDs,]
    
    #nrow(rbind(trainZeroes, testZeroes, trainOnes, testOnes)) == nrow(full_real_both) #Making sure we're not losing anything
    balanced <- rbind(ones, keptZeroes)
    
    balanced_IDs <- sample(x=1:nrow(balanced),size=round(nrow(balanced)*0.8), replace=F) #subsample out 80% of our edges. 
    test <- balanced[-c(balanced_IDs),] #assign 0% train set
    train <- balanced[balanced_IDs,] #assign 80% train set
  }
    
  if(class_balancing==FALSE){
       # Just Subsample our edgelist as is-don't do any balancing
    sample_IDs <- sample(x=1:nrow(full_real_both), size=round(nrow(full_real_both)*0.8), replace=F) #subsample out 80% of our edges. 
    test <- full_real_both[-sample_IDs,] #assign 80% train set
    train <- full_real_both[sample_IDs,]
  }

  rf<-randomForest::randomForest(real ~. -Frugivore_Species - Plant_Species, data=train, ntree=100)
  trainROC <- roc(train$real,rf$votes[,2])
  predictions <- stats::predict(rf, newdata=test, type="prob")
  test$S <- predictions[,2]
  
  if(returnTestTrain==TRUE){
    model=list(rfModel=rf,test=test, train=train)
  }
  if(returnTestTrain==FALSE){
    model<- rf
  }
  return(model)
}
```

Run 100 times!
```{r}
output <- list()
for(i in 1:100){
  #Set up Phylogeny
  frug_litter <- PVR::PVRdecomp(phy=Bird_trees[[round(i)]], type="newick", scale=TRUE)
  frug_PhyEig <-data.frame(Bird_trees[[5]]$tip.label, frug_litter@Eigen$vectors[,1:3]) #take first three vectors and make them a dataframe
  colnames(frug_PhyEig) <- c("Frugivore_Species", "fc1", "fc2", "fc3")
  frug_PhyEig$Frugivore_Species <- gsub(pattern="_", replace=" ", x=frug_PhyEig$Frugivore_Species) 
  birds_temp <- left_join(birds, frug_PhyEig, by="Frugivore_Species") #Make a new object that includes our phylo information
  
  rebalancedRF_Phy <- woodedWalk(birds_temp, FrugTraits = c(f_phylo), PlantTraits = c(p_phylo), class_balancing = TRUE)
  rebalancedRF_Traits <- woodedWalk(birds_temp, FrugTraits = c(f_traits), PlantTraits = c(p_traits), class_balancing = TRUE)
  rebalancedRF_Latent <- woodedWalk(birds_temp, FrugTraits = c(f_latent), PlantTraits = c(p_latent), class_balancing = TRUE)
  rebalancedRF_PhyTraits <- woodedWalk(birds_temp, FrugTraits = c(f_phylo, f_traits), PlantTraits = c(p_phylo, p_traits), class_balancing = TRUE)
  rebalancedRF_TraitsLatent <- woodedWalk(birds_temp, FrugTraits = c(f_latent, f_traits), PlantTraits = c(p_latent, p_traits), class_balancing = TRUE)
  rebalancedRF_PhyLatent <- woodedWalk(birds_temp, FrugTraits = c(f_latent, f_phylo), PlantTraits = c(p_latent, p_phylo), class_balancing = TRUE)
  rebalancedRF_Trio <- woodedWalk(birds_temp, FrugTraits = c(f_phylo, f_latent, f_traits), PlantTraits = c(p_phylo, p_latent, p_traits), class_balancing = TRUE)
  
  temp <- list(Phy=rebalancedRF_Phy, 
               Traits=rebalancedRF_Traits,
               Latent=rebalancedRF_Latent,
               PhyTraits=rebalancedRF_PhyTraits,
               TraitsLatent=rebalancedRF_TraitsLatent,
               PhyLatent=rebalancedRF_PhyLatent,
               Trio=rebalancedRF_Trio,
               run=i
               )
  output[[i]] <- temp
}


#save(output, file="ReplicateRF.Rda")
```

Variable importance plot
```{r}
temp <- NULL
for(i in 1:100){
temp <- rbind(temp, data.frame(giniDec=output[[i]]$Phy[[2]], model="Phy", run=i, trait=rownames(output[[i]]$Phy[[2]])))

temp <- rbind(temp, data.frame(giniDec=output[[i]]$Traits[[2]], model="Traits", run=i, trait=rownames(output[[i]]$Traits[[2]])))

temp <- rbind(temp, data.frame(giniDec=output[[i]]$Latent[[2]], model="Latent", run=i, trait=rownames(output[[i]]$Latent[[2]])))

temp <- rbind(temp, data.frame(giniDec=output[[i]]$PhyTraits[[2]], model="PhyTraits", run=i, trait=rownames(output[[i]]$PhyTraits[[2]])))

temp <- rbind(temp, data.frame(giniDec=output[[i]]$TraitsLatent[[2]], model="TraitsLatent", run=i, trait=rownames(output[[i]]$TraitsLatent[[2]])))

temp <- rbind(temp, data.frame(giniDec=output[[i]]$PhyLatent[[2]], model="PhyLatent", run=i, trait=rownames(output[[i]]$PhyLatent[[2]])))

temp <- rbind(temp, data.frame(giniDec=output[[i]]$Trio[[2]], model="Trio", run=i, trait=rownames(output[[i]]$Trio[[2]])))
}

varimport <- temp

#varimporSummary <- varimport %>% dplyr::group_by(., model, trait) %>% dplyr::summarise(avg=(mean(MeanDecreaseGini)/max(MeanDecreaseGini)), sd=sd((MeanDecreaseGini)/MeanDecreaseGini))

varimporSummary <- varimport %>% dplyr::group_by(., model, trait) %>% dplyr::summarise(avg=(mean(MeanDecreaseGini)), sd=sd((MeanDecreaseGini)))

varimporSummary$trait %<>% as.factor()
```


```{r}

Trio_Colors <- c("#E411E0", "#E0E411", "#11E0E4") #Phylo, Trait, Latent

colKey <- vector(mode="character", length=nrow(varimporSummary))
colKey[levels(varimporSummary$trait) %in% c(f_phylo, p_phylo)==TRUE] <- Trio_Colors[1]
colKey[levels(varimporSummary$trait) %in% c(f_traits, p_traits)==TRUE] <- Trio_Colors[2]
colKey[levels(varimporSummary$trait) %in% c(f_latent, p_latent)==TRUE] <- Trio_Colors[3]

levels(varimporSummary$trait)[match("Psvd1",levels(varimporSummary$trait))] <- "Plant SVD: Axis 1"
levels(varimporSummary$trait)[match("Psvd2",levels(varimporSummary$trait))] <- "Plant SVD: Axis 2"
levels(varimporSummary$trait)[match("Psvd3",levels(varimporSummary$trait))] <- "Plant SVD: Axis 3"
levels(varimporSummary$trait)[match("Fsvd1",levels(varimporSummary$trait))] <- "Frugivore SVD: Axis 1"
levels(varimporSummary$trait)[match("Fsvd2",levels(varimporSummary$trait))] <- "Frugivore SVD: Axis 2"
levels(varimporSummary$trait)[match("Fsvd3",levels(varimporSummary$trait))] <- "Frugivore SVD: Axis 3"

levels(varimporSummary$trait)[match("c1PlDecomp",levels(varimporSummary$trait))] <- "Plant Phylogeny: Axis 1"
levels(varimporSummary$trait)[match("c2PlDecomp",levels(varimporSummary$trait))] <- "Plant Phylogeny: Axis 2"
levels(varimporSummary$trait)[match("c3PlDecomp",levels(varimporSummary$trait))] <- "Plant Phylogeny: Axis 3"
levels(varimporSummary$trait)[match("c4PlDecomp",levels(varimporSummary$trait))] <- "Plant Phylogeny: Axis 4"
levels(varimporSummary$trait)[match("fc1",levels(varimporSummary$trait))] <- "Frugivore Phylogeny: Axis 1"
levels(varimporSummary$trait)[match("fc2",levels(varimporSummary$trait))] <- "Frugivore Phylogeny: Axis 2"
levels(varimporSummary$trait)[match("fc3",levels(varimporSummary$trait))] <- "Frugivore Phylogeny: Axis 3"

levels(varimporSummary$trait)[match("Frug_Mean_Gape_Size",levels(varimporSummary$trait))] <- "Frugivore Gape Size"
levels(varimporSummary$trait)[match("Frug_Body_Mass",levels(varimporSummary$trait))] <- "Frugivore Mass"
levels(varimporSummary$trait)[match("fruit_diameter",levels(varimporSummary$trait))] <- "Fruit Diameter"
levels(varimporSummary$trait)[match("fruit_length",levels(varimporSummary$trait))] <- "Fruit Length"
levels(varimporSummary$trait)[match("red",levels(varimporSummary$trait))] <- "Red Fruit"
levels(varimporSummary$trait)[match("black",levels(varimporSummary$trait))] <- "Black Fruit"
levels(varimporSummary$trait)[match("green",levels(varimporSummary$trait))] <- "Green Fruit"
levels(varimporSummary$trait)[match("yellow",levels(varimporSummary$trait))] <- "Yellow Fruit"
levels(varimporSummary$trait)[match("brown",levels(varimporSummary$trait))] <- "Brown Fruit"
levels(varimporSummary$trait)[match("tree",levels(varimporSummary$trait))] <- "Tree"
levels(varimporSummary$trait)[match("palm",levels(varimporSummary$trait))] <- "Palm"
levels(varimporSummary$trait)[match("liana",levels(varimporSummary$trait))] <- "Liana"
levels(varimporSummary$trait)[match("scrub",levels(varimporSummary$trait))] <- "Scrub"

levels(varimporSummary$trait)[match("LipScore1",levels(varimporSummary$trait))] <- "Low Lipid Content Fruit"
levels(varimporSummary$trait)[match("LipScore2",levels(varimporSummary$trait))] <- "Mid Lipid Content Fruit"
levels(varimporSummary$trait)[match("LipScore3",levels(varimporSummary$trait))] <- "High Lipid Content Fruit"

levels(varimporSummary$trait)[match("FrugScore1",levels(varimporSummary$trait))] <- "Occasional Frugivore"
levels(varimporSummary$trait)[match("FrugScore2",levels(varimporSummary$trait))] <- "Facultative Frugivore"
levels(varimporSummary$trait)[match("FrugScore3",levels(varimporSummary$trait))] <- "Strict Frugivore"



```

```{r}
varimporSummary$trait %<>% as.factor()

varimporSummary$model <- as.factor(varimporSummary$model)

trio <- varimporSummary %>% dplyr::filter(., model=="Trio")
varimporSummary$trait <- factor(varimporSummary$trait, levels=trio[order(trio$avg),]$trait)


#pdf(file="VarImportance_ErrBars.pdf", width=11, height=11)
ggplot(data=varimporSummary, aes(y=trait, x=avg, fill=model))+geom_col(position = position_dodge(), width = 0.9)+theme_classic()+
  scale_fill_manual(values = alpha(c("Phy" = "#E411E0",
                                "Traits" = "#E0E411",
                                "Latent" = "#11E0E4",
                                "PhyTraits" = "#E27B79",
                                "TraitsLatent" = "#79E27B",
                                "PhyLatent" = "#7B79E2",
                                "Trio" = "#000000"
                                ), 1.0))+
  geom_errorbar(aes(xmin=avg-sd, xmax=avg+sd), width=.2,
                 position=position_dodge(.9))+
    theme(axis.text.y = element_text(colour = colKey, size = 15), legend.position = "none")

#pdf(file="VarImportance_Dots_ErrBars.pdf", width=11, height=11)
ggplot(data=varimporSummary, aes(y=trait, x=avg, col=model))+geom_point(size=5,)+theme_classic()+
  scale_color_manual(values = alpha(c("Phy" = "#E411E0",
                                "Traits" = "#E0E411",
                                "Latent" = "#11E0E4",
                                "PhyTraits" = "#E27B79",
                                "TraitsLatent" = "#79E27B",
                                "PhyLatent" = "#7B79E2",
                                "Trio" = "#000000"
                                ), 1.0))+
  geom_errorbar(aes(xmin=avg-sd, xmax=avg+sd), width=.2, color="dark grey", position = position_dodge(width=0.9))+
    theme(axis.text.y = element_text(colour = colKey, size = 15), legend.position = "none")


ggplot(data=output_niceName, aes(y=Variable, x=MeanDecreaseGini, col=model))+geom_point(size=5)+theme_classic()+
  scale_color_manual(values = alpha(c("Phy_rf" = "#E411E0",
                                "Traits_rf" = "#E0E411",
                                "Latent_rf" = "#11E0E4",
                                "PhyTraits_rf" = "#E27B79",
                                "TraitsLatent_rf" = "#79E27B",
                                "PhyLatent_rf" = "#7B79E2",
                                "Trio_rf" = "#000000"
                                ), 1.0))+
    theme(axis.text.y = element_text(colour = colKey, size = 15), legend.position = "none")
```

```{r}
temp <- NULL
for(i in 1:100){
temp <- rbind(temp, data.frame(AUC=output[[i]]$Phy[[1]], model="Phy", run=i))

temp <- rbind(temp, data.frame(AUC=output[[i]]$Traits[[1]], model="Traits", run=i))

temp <- rbind(temp, data.frame(AUC=output[[i]]$Latent[[1]], model="Latent", run=i))

temp <- rbind(temp, data.frame(AUC=output[[i]]$PhyTraits[[1]], model="PhyTraits", run=i))

temp <- rbind(temp, data.frame(AUC=output[[i]]$TraitsLatent[[1]], model="TraitsLatent", run=i))

temp <- rbind(temp, data.frame(AUC=output[[i]]$PhyLatent[[1]], model="PhyLatent", run=i))

temp <- rbind(temp, data.frame(AUC=output[[i]]$Trio[[1]], model="Trio", run=i))
}

Performance <- temp
PerformanceSummary <- Performance %>% dplyr::group_by(., model) %>% dplyr::summarise(avgAUC=(mean(AUC)), sd=sd((AUC)))
```

